name: common-setup
description: Common environment setup

inputs:
  GITHUB_TOKEN:
    description: "GitHub Token for container registry login"
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

    - shell: bash
      run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"

    - shell: bash
      run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.GITHUB_TOKEN }}

    # - name: Extract metadata (tags, labels) for Docker
    #   id: meta
    #   uses: docker/metadata-action@v4
    #   with:
    #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
    #     flavor: |
    #       latest=true
