name: sunlei/futu-opend
run-name: 🚀 Building docker image ${{ github.workflow }} by @${{ github.actor }}

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - master
    paths:
      - "futu-opend/Dockerfile"
      - ".github/workflows/futu-opend.yml"
  workflow_dispatch:
    inputs:
      trigger:
        description: "Manually trigger"
        required: true
        type: choice
        options:
          - build

env:
  REGISTRY: ghcr.io

jobs:
  futu-opend:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Checkout repository
        # https://github.com/actions/checkout
        uses: actions/checkout@v4

      - name: Common setup
        uses: ./.github/actions/common-setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image | LATEST | ${{ env.LATEST_VERSION_RELEASE }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ github.job }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.workflow }}:latest

      - run: echo "🍏 This job's status is ${{ job.status }}."
