name: sunlei/gost
run-name: 🚀 Building docker image ${{ github.workflow }} by @${{ github.actor }}

on:
  schedule:
    - cron: "0 5 * * *"
  push:
    branches:
      - master
    paths:
      - "gost/Dockerfile"
      - ".github/workflows/gost.yml"
  workflow_dispatch:
    inputs:
      trigger:
        description: "Manually trigger"
        required: true
        type: choice
        options:
          - build

env:
  REGISTRY: ghcr.io

jobs:
  gost:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest version
        run: |
          # latest stable
          LATEST_VERSION_STABLE=$(curl -sfL "https://api.github.com/repos/go-gost/gost/releases/latest" | jq --raw-output '.tag_name | ltrimstr("v")')
          # latest release
          LATEST_VERSION_RELEASE=$(curl -sfL "https://api.github.com/repos/go-gost/gost/releases" | jq --raw-output '.[0].tag_name | ltrimstr("v")')

          echo "LATEST_VERSION_STABLE=$LATEST_VERSION_STABLE" >> $GITHUB_ENV
          echo "LATEST_VERSION_RELEASE=$LATEST_VERSION_RELEASE" >> $GITHUB_ENV

      - name: Build and push docker image | STABLE | ${{ env.LATEST_VERSION_STABLE }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ github.job }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          build-args: |
            VERSION=${{ env.LATEST_VERSION_STABLE }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.workflow }}:stable
          # tags: ${{ steps.meta.outputs.tags }}
          # labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push docker image | LATEST | ${{ env.LATEST_VERSION_RELEASE }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ github.job }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: true
          build-args: |
            VERSION=${{ env.LATEST_VERSION_RELEASE }}
          tags: |
            ${{ env.REGISTRY }}/${{ github.workflow }}:latest

      - run: echo "🍏 This job's status is ${{ job.status }}."
